apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-k8s-deploy
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 887905533173.dkr.ecr.ap-south-1.amazonaws.com/ravik:javamulti
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Change to NodePort or ClusterIP if needed